version: "3.3"
services:
  websecdemos:
    build: .
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      AWS_ACCESS_KEY_ID: "" # replace with your AWS access key
      AWS_SECRET_ACCESS_KEY: "" # replace with your AWS secret key
      AWS_S3_BUCKET_NAME: "mdmsecretstuff"